// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	rents "rentRoom/businesses/rents"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, page, perpage
func (_m *Usecase) Fetch(ctx context.Context, page int, perpage int) ([]rents.Domain, int, error) {
	ret := _m.Called(ctx, page, perpage)

	var r0 []rents.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []rents.Domain); ok {
		r0 = rf(ctx, page, perpage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rents.Domain)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, perpage)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, perpage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAll provides a mock function with given fields: ctx
func (_m *Usecase) GetAll(ctx context.Context) ([]rents.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []rents.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []rents.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rents.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, rentsDomain
func (_m *Usecase) Store(ctx context.Context, rentsDomain *rents.Domain) (rents.Domain, error) {
	ret := _m.Called(ctx, rentsDomain)

	var r0 rents.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *rents.Domain) rents.Domain); ok {
		r0 = rf(ctx, rentsDomain)
	} else {
		r0 = ret.Get(0).(rents.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *rents.Domain) error); ok {
		r1 = rf(ctx, rentsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, rentsDomain
func (_m *Usecase) Update(ctx context.Context, rentsDomain *rents.Domain) (*rents.Domain, error) {
	ret := _m.Called(ctx, rentsDomain)

	var r0 *rents.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *rents.Domain) *rents.Domain); ok {
		r0 = rf(ctx, rentsDomain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rents.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *rents.Domain) error); ok {
		r1 = rf(ctx, rentsDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
