swagger: "2.0"
info:
  description: This is a Rent Room API
  version: 1.0.0
  title: Rent Room App API
  # put the contact info for your development or API team
  contact:
    email: alfilailisaad@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
  - name: users
  - name: rooms
  - name: buildings
  - name: rents

paths:
  /users/login:
    post:
      tags:
        - users
      produces:
        - application/json
      parameters:
        - in: body
          name: login
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  username:
                    type: string
                  user_type:
                    type: string
                  role:
                    type: string
                  token:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        400:
          description: bad input parameter
  /users/register:
    post:
      tags:
        - users
      produces:
        - application/json
      parameters:
        - in: body
          name: login
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              name:
                type: string
              user_type:
                type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                $ref: "#/definitions/User"
        400:
          description: bad input parameter

  /rooms/list:
    get:
      tags:
        - rooms
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: success add response
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                $ref: "#/definitions/Rooms"
        400:
          description: bad input parameter
  /rooms/store:
    post:
      tags:
        - rooms
      produces:
        - application/json

      parameters:
        - in: body
          name: rooms
          schema:
            type: object
            properties:
              rooms_name:
                type: string
              rent_status:
                type: boolean
              rent_price:
                type: integer
              buildin_id:
                type: integer
      responses:
        200:
          description: search results matching criteria
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                type: array
                items:
                  $ref: "#/definitions/Rooms"
        400:
          description: bad input parameter
  /rooms/update:
    put:
      tags:
        - rooms
      produces:
        - application/json

      parameters:
        - in: body
          name: rooms
          schema:
            type: object
            properties:
              id:
                type: integer
              rent_status:
                type: boolean
      responses:
        200:
          description: search results matching criteria
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                type: array
                items:
                  $ref: "#/definitions/Rooms"
        400:
          description: bad input parameter
  /buildings/store:
    post:
      tags:
        - buildings
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            type: object
            properties:
              building_name:
                type: string
              building_addr:
                type: string
      responses:
        200:
          description: success add response
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                $ref: "#/definitions/Building"
        400:
          description: bad input parameter
  /buildings/list:
    get:
      tags:
        - buildings
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                type: array
                items:
                  $ref: "#/definitions/Building"
        400:
          description: bad input parameter

  /rents/store:
    post:
      tags:
        - rents
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            type: array
            items:
              type: object
              properties:
                user_id:
                  type: string
                room_id:
                  type: string
                jumlah_bayar:
                  type: integer
                tanggal_pinjam:
                  type: string
                status_pinjam:
                  type: boolean
      responses:
        200:
          description: success add response
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                $ref: "#/definitions/Rents"
        400:
          description: bad input parameter
  /rents/list:
    get:
      tags:
        - rents
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                type: array
                items:
                  $ref: "#/definitions/Rents"
        400:
          description: bad input parameter

  /rents/update:
    put:
      tags:
        - rents
      produces:
        - application/json

      parameters:
        - in: body
          name: rooms
          schema:
            type: object
            properties:
              id:
                type: integer
              status_pinjam:
                type: boolean
      responses:
        200:
          description: search results matching criteria
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  rc:
                    type: integer
                  message:
                    type: string
              data:
                type: array
                items:
                  $ref: "#/definitions/Rents"
        400:
          description: bad input parameter

definitions:
  User:
    type: object
    required:
      - name
      - username
      - user_type
      - role
      - token
      - created_at
      - updated_at
    properties:
      id:
        type: integer
        format: int64
        example: 1
      name:
        type: string
        example: alfi
      username:
        type: string
        example: alfilaili
      user_type:
        type: string
        example: 1
      token:
        type: string
        example: rtyuijksdbcvshsdghgshdgshgdsjgjh
      updated_at:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      created_at:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
  Building:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      building_name:
        type: string
        example: uranus
      building_addr:
        type: string
        example: jln. in aja
      updated_at:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      created_at:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
  Rooms:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      room_name:
        type: string
        example: uranus
      rent_status:
        type: boolean
        example: true
      room_price:
        type: integer
        example: 10000
      building_id:
        type: integer
        example: 1
      building_name:
        type: string
        example: uranus
      updated_at:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      created_at:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z

  Rents:
    type: object
    properties:
      id:
        type: integer
      room_id:
        type: integer
      jumlah_pinjam:
        type: integer
      tanggal_pinjam:
        type: string
      status_pinjam:
        type: boolean

  # Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /khoiruttamimi/shoe-store/1.0.0
schemes:
  - https
# Added by API Auto Mocking Plugin
basePath: /alfilailisaadahr/rentRoom/1.0.0
